CREATE DATABASE logs;

USE logs;

CREATE TABLE files_logs (
	`id` INT(100) NOT NULL AUTO_INCREMENT,
	`dir` VARCHAR(255) NOT NULL,
	`file` VARCHAR(255) NOT NULL,
	`action` VARCHAR(255) NOT NULL,
	`created_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
);